version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 40
  - package-ecosystem: "github-actions"
    directory: ""
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 40
